// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonAction: typeof import('./src/components/ButtonAction.vue')['default']
    ButtonLink: typeof import('./src/components/ButtonLink.vue')['default']
    EmailInput: typeof import('./src/components/EmailInput.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NameInput: typeof import('./src/components/NameInput.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
  }
}

export { }
